export { default as EmployeePage } from './EmployeePage/EmployeePage'
export { default as HomePage } from './HomePage/HomePage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as RegistrationPage } from './RegistrationPage/RegistrationPage'
export { default as Page404 } from './Page404/Page404'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
